//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Caterory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Caterory()
        {
            this.tbl_Expense = new HashSet<tbl_Expense>();
            this.tbl_Income = new HashSet<tbl_Income>();
        }
    
        public int catryID { get; set; }
        public string catryTitle { get; set; }
        public string catDesp { get; set; }
        public string imgUrl { get; set; }
        public int userID { get; set; }
        public bool isActive { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Expense> tbl_Expense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Income> tbl_Income { get; set; }
    }
}
